/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/Auth/Login': RouteRecordInfo<'/Auth/Login', '/Auth/Login', Record<never, never>, Record<never, never>>,
    '/Dashboard': RouteRecordInfo<'/Dashboard', '/Dashboard', Record<never, never>, Record<never, never>>,
    '/Produtos/ListaProdutos': RouteRecordInfo<'/Produtos/ListaProdutos', '/Produtos/ListaProdutos', Record<never, never>, Record<never, never>>,
    '/Produtos/NovoProduto': RouteRecordInfo<'/Produtos/NovoProduto', '/Produtos/NovoProduto', Record<never, never>, Record<never, never>>,
  }
}
